# -*- coding: utf-8 -*-
"""Iris Classfiers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rexmZoHkgnnaFCVeZsM-yYCYjBFjdoSS
"""

#Import Utility Packages#
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

#Import Classifiers#
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import plot_tree, DecisionTreeClassifier

#Load Data#
iris = sns.load_dataset("iris")

#EDA#
print("Dataframe Head\n",iris.head(),"\n\nCorr Matrix\n", iris.corr(),"\n\nPairPlot\n", sns.pairplot(iris, hue='species'))

# Prepare Data #
vals = iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
labels = iris["species"]

assert vals.shape[0] == labels.shape[0]

#Split Data#
X_train, Y_train, x_test, y_test = train_test_split(vals, labels, random_state=1991, train_size=0.8)

#K Nearest Neighbours#

C = KNeighborsClassifier(n_neighbors=3)
C.fit(X_train, x_test)

KNN_Score = C.score(Y_train, y_test)

print(round(KNN_Score, 3))

#Decision Tree#
tree = DecisionTreeClassifier()
tree.fit(X_train, x_test)

Tree_Score = tree.score(Y_train,y_test)

plt.figure(figsize=(15,15))
print("\n\nDecision Tree\n", plot_tree(tree, feature_names=vals.columns ,class_names=labels.unique()))

print(round(Tree_Score, 3))

